### ISSUE TITLE
Project name improvement suggestion

### ISSUE THREAD

**Issue by whip113** [conjurdemos/Accelerator-PAS-Automation#2]
The current project name suggests that this project includes capabilities for automating PAS in a general sense. As this project is more about automating the onboarding aspects, I think a more descriptive name would be something like "Accelerator-PAM-Onboarding". Eventually, there will be several Accelerators for PAS automation and that collection of Accelerators would then be labeled "PAS Automation". Thank you for your consideration!

**Comment by jodyhuntatx** [comment]
Renamed to Accelerator-PAM-Onboarding
